### PR TITLE
Make sure that ALSA pipe FDs are closed

### LINKED ISSUE #173: Critical: file descriptors leak in ALSA when MidiInput::connect() fails
https://github.com/Boddlnagg/midir/blob/0aaa829ba6ea5aaf1ed298d0cb9227e4820859a2/src/backend/alsa/mod.rs#L279

Here there are file descriptors allocated via `pipe(2)` which are not released in case of error.

This is really bad in an application that will periodically try to connect to a busy midi controller.

Also there's probably no need for using pipes here, there are likely better synchronization alternatives.

### PR DESCRIPTION
**Pull request by Boddlnagg**
Fixes #173

### CODE REVIEW

File: src/backend/alsa/mod.rs [hunk 1]
```diff
@@ -153,17 +153,32 @@ pub struct MidiInputConnection<T: 'static> {
...
 struct HandlerData<T: 'static> {
     ignore_flags: Ignore,
     seq: Seq,
-    trigger_rcv_fd: i32,
+    trigger_rcv_fd: Option<PipeFd>,
     callback: Box<dyn FnMut(u64, &[u8], &mut T) + Send>,
     queue_id: i32, // an input queue is needed to get timestamped events
 }
 
+#[repr(transparent)]
```
Comment (abique) [inline src/backend/alsa/mod.rs]: I'm not sure why this is needed.

File: src/backend/alsa/mod.rs [hunk 2]
```diff
@@ -153,17 +153,32 @@ pub struct MidiInputConnection<T: 'static> {
...
+struct PipeFd(i32);
```
Comment (abique) [inline src/backend/alsa/mod.rs]: I would name it `AutoClosingFd` instead of `PipeFd`.

File: src/backend/alsa/mod.rs [hunk 3]
```diff
@@ -153,17 +153,32 @@ pub struct MidiInputConnection<T: 'static> {
...
+
+impl PipeFd {
+    fn get(&self) -> i32 {
+        self.0
```
Comment (abique) [inline src/backend/alsa/mod.rs]: You probably want to assert that `self.0 >= 0` before returning.

File: src/backend/alsa/mod.rs [hunk 4]
```diff
@@ -153,17 +153,32 @@ pub struct MidiInputConnection<T: 'static> {
...
+    }
+}
+
+impl Drop for PipeFd {
+    fn drop(&mut self) {
+        unsafe { libc::close(self.0); }
```
Comment (abique) [inline src/backend/alsa/mod.rs]: Again you certainly want to assert that `self.0 >= 0` before closing.

File: src/backend/alsa/mod.rs (hunk 3 above)
Comment (Boddlnagg) [reply src/backend/alsa/mod.rs]: I don't need to assert that if nobody has changed the value since construction.

File: src/backend/alsa/mod.rs [hunk 5]
```diff
@@ -489,11 +505,9 @@ impl<T> MidiInputConnection<T> {
                 .unsubscribe_port(subscription.get_sender(), subscription.get_dest());
         }
 
-        // Close the trigger fds (TODO: make sure that these are closed even in the presence of panic in thread)
-        unsafe {
-            libc::close(handler_data.trigger_rcv_fd);
-            libc::close(self.trigger_send_fd);
-        }
+        // Close the trigger fds
+        drop(handler_data.trigger_rcv_fd.take());
```
[the remark this answers is not in the document]
Comment (Boddlnagg) [reply src/backend/alsa/mod.rs]: Good point, I'll change that (and the subsequent line).

File: src/backend/alsa/mod.rs [hunk 6]
```diff
@@ -755,7 +769,7 @@ fn handle_input<T>(mut data: HandlerData<T>, user_data: &mut T) -> HandlerData<T
     let poll_desc_info = (&data.seq, Some(Direction::Capture));
     let mut poll_fds = vec![INVALID_POLLFD; poll_desc_info.count() + 1];
     poll_fds[0] = pollfd {
-        fd: data.trigger_rcv_fd,
+        fd: data.trigger_rcv_fd.as_ref().unwrap().get(),
```
[the remark this answers is not in the document]
Comment (Boddlnagg) [reply src/backend/alsa/mod.rs]: Yes, it's needed, because I don't have ownership here, so I cannot `unwrap()` the the original `Option<PipeFd>`, and I need to unwrap to be able to call `get()`.

**Comment by Boddlnagg** [comment]
Were you able to test this PR successfully (by running an example program or your own program)?

**Comment by abique** [comment]
Fix confirmed.

Both the successful connect and unsuccessful one are working fine.
